export const TwixTheme = {
  colors: {
    primary: '#c8b1e4',
    accent: '#a468ec',
    'label-text': '#10002b',
    'root-bg': '#f9f6ff',
    'root-text': '#10002b',
    'root-border': '#c8b1e4',
    'folder-text': '#f9f6ff',
    'folder-border': '#c8b1e4',
    'folder-title-bg': '#c8b1e4',
    'input-text': '#10002b',
    'input-border': '#e9dbf9',
    'input-hover-border': '#c8b1e4',
    'input-focus-border': '#9b72cf',
    'input-active-bg': '#e9dbf9',
    'button-text': '#10002b',
    'button-bg': '#fff',
    'select-bg': '#fff',
    selection: '#c8b1e4',
  },
  radii: {
    input: 2,
    root: 2,
  },
  space: {
    input: 6,
    'folder-h': 6,
    'folder-v': 3,
    'row-h': 3,
    'row-v': 3,
    'col-gap': 3,
  },
  fonts: {
    mono: `ui-monospace, SFMono-Regular, Menlo, 'Roboto Mono', monospace`,
  },
  fontSizes: {
    root: 11,
  },
  sizes: {
    'root-width': 280,
    'scrubber-width': 6,
    'scrubber-height': 14,
    'row-height': 25,
    'joystick-width': 100,
    'joystick-height': 100,
  },
  shadows: {
    root: '0 0 40px #00000033',
    overlay: '0 4px 14px #00000033',
  },
  borderWidths: {
    input: 1,
    root: 0,
    folder: 4,
  },
  fontWeights: {
    folder: 600,
    label: 600,
  },
  transitions: {
    border: 'border-color 250ms ease',
    bg: 'background-color 250ms ease',
    'border-bg': 'border-color, background-color 250ms ease',
  },
}
